apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /graphql
        backend:
          serviceName: jide-api
          servicePort: 80
      - path: /
        backend:
          serviceName: jide-web
          servicePort: 80
